version: '3'

vars:
  APP_NAME: textproof
  BUILD_DIR: build
  DATA_DIR: data
  PORT: 8080
  DIFFICULTY: 4
  MAIN_FILE: cmd/server/main.go

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: Показать справку
    cmds:
      - task --list

  # =====================================================================
  # УСТАНОВКА И НАСТРОЙКА
  # =====================================================================

  install-tools:
    desc: Установить необходимые инструменты (templ, swag, air)
    cmds:
      - echo "Установка инструментов..."
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/air-verse/air@latest
      - echo "✓ Инструменты установлены"

  deps:
    desc: Установить зависимости проекта
    cmds:
      - echo "Установка зависимостей..."
      - go mod download
      - go mod verify
      - echo "✓ Зависимости установлены"

  setup:
    desc: Полная настройка проекта (инструменты + зависимости + генерация)
    cmds:
      - task: install-tools
      - task: deps
      - task: generate
      - echo "✓ Проект готов к работе!"
      - echo "Запустите 'task run' для старта сервера"

  # =====================================================================
  # ГЕНЕРАЦИЯ
  # =====================================================================

  templ:
    desc: Сгенерировать Templ шаблоны
    cmds:
      - echo "Генерация Templ шаблонов..."
      - templ generate
      - echo "✓ Templ шаблоны сгенерированы"

  swagger:
    desc: Сгенерировать Swagger документацию
    cmds:
      - echo "Генерация Swagger документации..."
      - swag init -g {{.MAIN_FILE}} -o docs --parseDependency --parseInternal --exclude web/templates
      - echo "✓ Swagger документация сгенерирована"
      - task: fix-docs

  fix-docs:
    desc: Исправить известную ошибку в docs/docs.go
    cmds:
      - go run scripts/fixdocs.go
    sources:
      - docs/docs.go
    silent: true

  generate:
    desc: Сгенерировать всё (templ + swagger)
    cmds:
      - task: templ
      - task: swagger
      - echo "✓ Генерация завершена"

  # =====================================================================
  # СБОРКА И ЗАПУСК
  # =====================================================================

  build:
    desc: Собрать приложение
    deps:
      - templ
    cmds:
      - echo "Сборка приложения..."
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-s -w" -o {{.BUILD_DIR}}/{{.APP_NAME}} {{.MAIN_FILE}}
      - echo "✓ Сборка завершена"
    sources:
      - '**/*.go'
      - '**/*.templ'
    generates:
      - '{{.BUILD_DIR}}/{{.APP_NAME}}'

  run:
    desc: Запустить сервер
    deps:
      - generate
    cmds:
      - echo "Запуск сервера..."
      - go run {{.MAIN_FILE}} -port {{.PORT}} -difficulty {{.DIFFICULTY}}

  dev:
    desc: Запустить в режиме разработки с hot reload (air)
    deps:
      - templ
    cmds:
      - echo "Режим разработки (hot reload)..."
      - air

  dev-modd:
    desc: Запустить в режиме разработки с modd
    cmds:
      - echo "Режим разработки (modd)..."
      - modd

  # =====================================================================
  # ТЕСТИРОВАНИЕ
  # =====================================================================

  test:
    desc: Запустить тесты
    cmds:
      - echo "Запуск тестов..."
      - go test -v ./...

  test-cover:
    desc: Запустить тесты с покрытием
    cmds:
      - echo "Запуск тестов с покрытием..."
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "✓ Отчёт о покрытии создан"

  test-race:
    desc: Запустить тесты с детектором гонок
    cmds:
      - echo "Запуск тестов с race detector..."
      - go test -race -v ./...

  bench:
    desc: Запустить бенчмарки
    cmds:
      - echo "Запуск бенчмарков..."
      - go test -bench=. -benchmem ./...

  # =====================================================================
  # КАЧЕСТВО КОДА
  # =====================================================================

  fmt:
    desc: Форматировать код
    cmds:
      - echo "Форматирование кода..."
      - go fmt ./...
      - templ fmt .
      - echo "✓ Код отформатирован"

  lint:
    desc: Проверить код линтером
    cmds:
      - echo "Проверка кода..."
      - golangci-lint run
      - echo "✓ Проверка завершена"

  vet:
    desc: Запустить go vet
    cmds:
      - echo "Запуск go vet..."
      - go vet ./...

  check:
    desc: Полная проверка (fmt + vet + lint + test)
    cmds:
      - task: fmt
      - task: vet
      - task: test
      - echo "✓ Все проверки пройдены"

  # =====================================================================
  # ОЧИСТКА
  # =====================================================================

  clean:
    desc: Очистить собранные файлы
    cmds:
      - echo "Очистка..."
      - rm -rf {{.BUILD_DIR}}
      - rm -rf docs
      - rm -f coverage.out coverage.html
      - find . -name "*_templ.go" -type f -delete
      - echo "✓ Очистка завершена"

  clean-data:
    desc: Удалить данные блокчейна (ОСТОРОЖНО!)
    prompt: Это удалит все данные блокчейна. Продолжить?
    cmds:
      - rm -rf {{.DATA_DIR}}
      - echo "✓ Данные удалены"

  # =====================================================================
  # DOCKER
  # =====================================================================

  docker-build:
    desc: Собрать Docker образ
    cmds:
      - echo "Сборка Docker образа..."
      - docker build -t {{.APP_NAME}}:latest .
      - echo "✓ Docker образ собран"

  docker-run:
    desc: Запустить в Docker
    cmds:
      - echo "Запуск в Docker..."
      - docker run -p {{.PORT}}:{{.PORT}} -v $(pwd)/{{.DATA_DIR}}:/app/{{.DATA_DIR}} {{.APP_NAME}}:latest

  docker-clean:
    desc: Очистить Docker артефакты
    cmds:
      - docker system prune -f
      - echo "✓ Docker очищен"

  # =====================================================================
  # УТИЛИТЫ
  # =====================================================================

  backup:
    desc: Создать бэкап данных
    cmds:
      - mkdir -p backups
      - tar -czf backups/backup-$(date +%Y%m%d-%H%M%S).tar.gz {{.DATA_DIR}}
      - echo "✓ Бэкап создан в backups/"

  restore:
    desc: Восстановить последний бэкап
    cmds:
      - |
        LATEST=$(ls -t backups/*.tar.gz | head -1)
        if [ -n "$LATEST" ]; then
          tar -xzf "$LATEST"
          echo "✓ Восстановлено из: $LATEST"
        else
          echo "✗ Бэкапы не найдены"
        fi

  stats:
    desc: Показать статистику проекта
    cmds:
      - echo "=== Статистика проекта ==="
      - echo "Строк кода (Go):"
      - find . -name "*.go" -not -path "./vendor/*" -not -name "*_templ.go" | xargs wc -l | tail -1
      - echo "Строк кода (Templ):"
      - find . -name "*.templ" | xargs wc -l | tail -1
      - echo "Файлов Go:"
      - find . -name "*.go" -not -path "./vendor/*" -not -name "*_templ.go" | wc -l
      - echo "Файлов Templ:"
      - find . -name "*.templ" | wc -l

  watch-logs:
    desc: Следить за логами (если они есть)
    cmds:
      - tail -f logs/*.log

  # =====================================================================
  # SWAGGER
  # =====================================================================

  swagger-serve:
    desc: Сгенерировать swagger и запустить сервер
    cmds:
      - task: swagger
      - task: run

  swagger-validate:
    desc: Валидировать Swagger спецификацию
    cmds:
      - echo "Валидация Swagger..."
      - swagger validate docs/swagger.yaml
      - echo "✓ Swagger спецификация валидна"

  # =====================================================================
  # PRODUCTION
  # =====================================================================

  prod-build:
    desc: Собрать для production
    cmds:
      - echo "Сборка для production..."
      - task: generate
      - mkdir -p {{.BUILD_DIR}}
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=$(git describe --tags --always)" -o {{.BUILD_DIR}}/{{.APP_NAME}}-linux-amd64 {{.MAIN_FILE}}
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=$(git describe --tags --always)" -o {{.BUILD_DIR}}/{{.APP_NAME}}-windows-amd64.exe {{.MAIN_FILE}}
      - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=$(git describe --tags --always)" -o {{.BUILD_DIR}}/{{.APP_NAME}}-darwin-amd64 {{.MAIN_FILE}}
      - CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=$(git describe --tags --always)" -o {{.BUILD_DIR}}/{{.APP_NAME}}-darwin-arm64 {{.MAIN_FILE}}
      - echo "✓ Production builds готовы"

  # =====================================================================
  # GIT
  # =====================================================================

  pre-commit:
    desc: Проверки перед коммитом
    cmds:
      - task: fmt
      - task: vet
      - task: test
      - echo "✓ Готово к коммиту"