// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "blockchain-verifier/web/templates/components"
import "blockchain-verifier/web/templates/components/atoms"

func Deposit() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DepositContent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DepositContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"columns is-centered\"><div class=\"column is-two-thirds\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header(components.HeaderParams{
			Title:    "Депонирование текста",
			Subtitle: "Зафиксируйте авторство вашего текста в блокчейне",
			Icon:     "fas fa-upload",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Простая форма --><div class=\"box\"><form id=\"deposit-form\" method=\"POST\" action=\"/api/deposit\"><!-- Автор --><div class=\"field\"><label class=\"label\">Автор (ФИО или псевдоним)</label><div class=\"control has-icons-left\"><input class=\"input\" type=\"text\" id=\"author\" name=\"author_name\" placeholder=\"Иванов Иван Иванович\" required> <span class=\"icon is-small is-left\"><i class=\"fas fa-user\"></i></span></div><p class=\"help\">Имя, под которым будет зафиксировано авторство</p></div><!-- Название --><div class=\"field\"><label class=\"label\">Название произведения</label><div class=\"control has-icons-left\"><input class=\"input\" type=\"text\" id=\"title\" name=\"title\" placeholder=\"Моя статья о блокчейне\" required> <span class=\"icon is-small is-left\"><i class=\"fas fa-heading\"></i></span></div><p class=\"help\">Краткое название или заголовок</p></div><!-- Текст --><div x-data=\"{ text: '' }\" class=\"field\"><label class=\"label\">Текст</label><div class=\"control\"><textarea class=\"textarea\" id=\"text\" name=\"text\" placeholder=\"Введите ваш текст здесь...\" rows=\"10\" required x-model=\"text\"></textarea></div><p class=\"help\">Длина текста в символах: <span x-text=\"text.length\"></span></p></div><!-- Публичный ключ (опционально) --><div class=\"field\"><label class=\"label\">Публичный ключ для подписи (опционально) <span class=\"tag is-light ml-2\">Необязательно</span></label><div class=\"control\"><textarea class=\"textarea\" id=\"public_key\" name=\"public_key\" placeholder=\"-----BEGIN PUBLIC KEY-----&#10;Ваш публичный ключ&#10;-----END PUBLIC KEY-----\" rows=\"4\"></textarea></div><p class=\"help\">Если хотите связать текст с вашей электронной подписью</p></div><!-- Важное примечание -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.WarningSection(components.WarningSectionParams{
			Title: "Важно:",
			Icon:  "fas fa-exclamation-circle",
			Content: []string{
				"Система не хранит ваш текст, только его криптографический отпечаток (хеш)",
				"Сохраните оригинал текста у себя — он нужен для будущих проверок",
				"Процесс депонирования займет несколько секунд (майнинг блока)",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Кнопка --><div class=\"field\"><div class=\"control\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = atoms.Button(atoms.ButtonParams{
			Icon:       "fas fa-upload",
			LinkText:   "Зафиксировать в блокчейне",
			ButtonType: "is-info",
			Attributes: templ.Attributes{
				"type": "submit",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
