// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "blockchain-verifier/web/templates/components"

func Home(statCards []components.StatsCardParams) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = HomeContent(statCards).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func HomeContent(statCards []components.StatsCardParams) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"columns is-centered\"><div class=\"column is-three-quarters\"><!-- Геройская секция -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.HeroSection(components.HeroSectionParams{
			Title:    "TextProof",
			Subtitle: "Система доказательства авторства текстов с использованием блокчейн-технологии",
			Icon:     "fas fa-fingerprint",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Карточки возможностей -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.FeatureCardsSection([]components.FeatureCardParams{
			{
				Icon:        "fas fa-upload",
				Title:       "Депонирование",
				Description: "Зафиксируйте авторство вашего текста в блокчейне. Получите уникальный идентификатор для доказательства.",
				Link:        "/deposit",
				LinkText:    "Депонировать",
			},
			{
				Icon:        "fas fa-search",
				Title:       "Проверка",
				Description: "Проверьте подлинность текста по идентификатору. Убедитесь, что текст не изменялся после фиксации.",
				Link:        "/verify",
				LinkText:    "Проверить",
			},
			{
				Icon:        "fas fa-shield-alt",
				Title:       "Безопасность",
				Description: "Используем технологию блокчейн для гарантии неизменности. Все записи защищены криптографически.",
				Link:        "/about",
				LinkText:    "Подробнее",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Статистика -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.StatsSection(statCards).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- Как это работает -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.HowItWorksSection(components.HowItWorksSectionParams{
			Title: "Как это работает",
			Steps: []components.HowItWorksStep{
				{
					Number: 1,
					Title:  "Вставляете текст",
					Text:   "Вы загружаете свой текст в систему. Система автоматически вычисляет уникальный криптографический хеш.",
				},
				{
					Number: 2,
					Title:  "Получаете ID",
					Text:   "Система генерирует уникальный идентификатор и временную метку фиксации.",
				},
				{
					Number: 3,
					Title:  "Запись в блокчейн",
					Text:   "Хеш вашего текста записывается в блокчейн вместе с временной меткой, что гарантирует неизменность.",
				},
				{
					Number: 4,
					Title:  "Проверка",
					Text:   "Позже вы или другие могут проверить, что текст не изменялся с момента фиксации.",
				},
			},
			NoteTitle: "Важно",
			NoteText: []string{
				"Система не хранит ваш текст. Только его криптографический отпечаток (хеш).",
				"Это гарантирует конфиденциальность: никто кроме вас не сможет прочитать текст, но все могут проверить его подлинность.",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
