// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "blockchain-verifier/web/templates/components/atoms"

// Секция бейджа для сайта
func BadgeSection(badgeURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<hr class=\"mt-6 mb-5\"><h3 class=\"title is-4 mb-4\">Бейдж для сайта</h3><div class=\"box has-background-info-light mb-5\"><p class=\"has-text-weight-bold mb-3\">Предпросмотр бейджа:</p><!-- Preview --><div class=\"has-text-centered mb-4\"><iframe src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(badgeURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/bage_section.templ`, Line: 14, Col: 18}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" style=\"border:0; width:100%; max-width:320px; height:320px;\" loading=\"lazy\"></iframe></div><!-- HTML code --><p class=\"has-text-weight-bold mb-3\">HTML-код бейджа:</p><div class=\"field\"><div class=\"control\"><textarea class=\"textarea is-family-monospace\" rows=\"6\" readonly><iframe src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(badgeURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/bage_section.templ`, Line: 28, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" style=\"border:0; width:320px; height:320px; overflow: hidden; border: none\" scrolling=\"no\"></iframe></textarea></div></div><!-- Copy --><div class=\"field\" x-data=\"{\r\n\t\tshow: false,\r\n\t\tcopy() {\r\n\t\t\tnavigator.clipboard.writeText(\r\n\t\t\t\tthis.$el.closest('.box').querySelector('textarea').value\r\n\t\t\t)\r\n\t\t\tthis.show = true\r\n\t\t\tsetTimeout(() => this.show = false, 2000)\r\n\t\t}\r\n\t}\"><div class=\"control is-relative\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = atoms.Button(atoms.ButtonParams{
			Icon:       "fas fa-copy",
			Link:       "#",
			LinkText:   "Скопировать HTML-код бейджа",
			ButtonType: "is-info",
			Attributes: templ.Attributes{
				"type":       "button",
				"x-on:click": "copy()",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- Tooltip --><div x-show=\"show\" x-transition.opacity.scale.80 @click=\"show = false\" class=\"notification is-success is-light is-size-7\" style=\"\r\n\t\t\t\tposition: absolute;\r\n\t\t\t\ttop: -2.5rem;\r\n\t\t\t\tright: 0;\r\n\t\t\t\tpadding: 0.4rem 0.75rem;\r\n\t\t\t\tcursor: pointer;\r\n\t\t\t\twhite-space: nowrap;\r\n\t\t\t\"><i class=\"fas fa-check mr-1\"></i> Код скопирован</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
